name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup OCaml 5.2.x
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.2.x
        dune-cache: true
        opam-disable-sandboxing: true

    - name: Pin avro-simple dependency
      run: opam pin add avro-simple git+https://github.com/tmcgilchrist/avro-simple.git#master --yes

    - name: Install dependencies
      run: opam install . --deps-only --with-test -y

    - name: Build project
      run: opam exec -- dune build

    - name: Build JavaScript
      run: opam exec -- dune build src/main.bc.js

    - name: Build server
      run: opam exec -- dune build server/server.exe

    - name: Build test data generator
      run: opam exec -- dune build test/generate_test_data.exe
